---
title: "Donovan Lab Code of Conduct - archived - v2020"
toc: false
search: false
---

The spirt of the lab is one of welcome and kindness. Consistent with the [ASU Charter, Mission, and Goals](https://www.asu.edu/about/charter-mission-and-values) that we are “measured not by whom we exclude, but rather by whom we include and how they succeed…” the Donovan lab is committed to increasing and supporting greater diversity, equity, inclusion, and justice for all in the sciences. We have ZERO tolerance for harassment, discrimination, or bullying by and/or of members of our community in any form.

We value collaboration, and are supportive of one another. Our goal is to fight against the norm of competitiveness in academia, when one of us succeeds we all succeed. Inclusive in this effort we support each other in our scientific endeavors by being generous with our time and ideas, credit each other for our contributions, and we celebrate success as often as we can for everyone in our lab and our larger community.

Openness and communication are critical. We use tools and active approaches to better our interactions and our science, and we believe that openness is fundamental to the progression of science. We share our data and work as openly as possible. If we unknowingly hurt or offend a member of our lab or community we will listen, offer apologies, and commit to learning and doing better.

Integrity is vital. We acknowledge that we have an important role as scientists and do not manipulate, steal, or disguise data or results.

Members of the lab and of our associated community who violate of this code of conduct will be approached by Dr. Donovan. If necessary the issue will be escalated to the relevant entities at Arizona State University. If you experience or observe a violation of this code of conduct, please contact Dr. Donovan. ASU also provides resources and modes for reporting [here](https://inclusion.asu.edu/resources/reporting-options).

Adapted from various documents available under CC BY 4.0, the Donovan Lab Code of Conduct is licensed under CC BY 4.0 by Dr. Mary Donovan and can be freely adopted or reproduced.\
