---
title: "Donovan Lab Code of Conduct - archived - v2023"
toc: false
search: false
---

**The spirit of the lab is welcoming, kind, and empathetic.** We love what we do and this is reflected in the care we put into the quality of our work and the strength of our partnerships.

**We value collaboration, and are supportive of one another.** Our goal is to fight against competitiveness in academia – when one of us succeeds, we all succeed. We support each other by encouraging creativity, being generous with our time and ideas, giving credit to each other for our contributions, and celebrating success for everyone in our lab and communities. While doing so, we are respectful of each other’s time and expertise.

**We are committed to open, honest, and consistent communication.** We are available to one another, receptive to ideas and feedback, and attentive to each other’s needs.

**Open science and integrity are vital to our work.** We believe that openness is fundamental to the progression of science; therefore, we strive for transparency by sharing our data and working openly to the best of our ability. We produce high quality work equally in service of our field, our communities, and the broader public that is widely communicated and accessible. We acknowledge that we have an important role as scientists and do not manipulate, steal, or disguise data or results.

**We acknowledge our privileges and responsibilities.** We listen and learn, and engage with the communities and ecosystems we work in to serve them with respect and reciprocity. We acknowledge that our data collection, research, and applications are being conducted in Indigenous spaces, and in each of the geographies where we work we do our homework and reflect on what we learn, and we commit to supporting Indigenous peoples and movements.

**The Donovan Lab strives to create an equitable, inclusive, and just space that fosters diversity.** We recognize there are barriers in place that require restructuring and are working to make lasting change to improve justice, equity, diversity, and inclusion in the sciences through our actions. This is consistent with the [ASU Charter, Mission, and Goals](https://www.asu.edu/about/charter-mission-and-values) that we are “measured not by whom we exclude, but rather by whom we include and how they succeed*,*” and are honored to be part of and contribute to an organization with such a mission. 

We respect each other, and we have ZERO tolerance for harassment, discrimination, or bullying by and/or of members of our community in any form. If we unknowingly hurt or offend a member of our lab or community we will listen, offer apologies, and commit to learning and doing better. Members of the lab and of our associated community who violate this code of conduct will be approached by Dr. Donovan. If necessary, the issue will be escalated to the relevant entities at Arizona State University. If you experience or observe a violation of this code of conduct, please contact Dr. Donovan. ASU also provides resources and other modes for reporting [here](https://inclusion.asu.edu/resources/reporting-options).

—————-

Adapted from various documents available under CC BY 4.0, the Donovan Lab Code of Conduct is licensed under CC BY 4.0 by Dr. Mary Donovan and can be freely adopted or reproduced.

—————--

This code of conduct is a living document that is edited continuously to represent the values of past and current members of the lab. In the spirit of transparency that is part of our values, we archive previous versions of the code of conduct here\
