---
title: "Interested in Joining the lab?"
toc: false
---
Thank you for your interest in the lab. This page will provide you with information about open positions and instructions for contacting me. Information for potential Masters students, PhD students, and postdocs are listed below. If there are funded positions available they will be posted here.

### **Graduate Students**

Please take a look at our [recent publications](https://donovan-lab-at-himb.github.io/HIMB_DonovanLab/about.html), and [our code of conduct](https://donovan-lab-at-himb.github.io/HIMB_DonovanLab/codeconduct.html). After that, if you believe that the lab is a good fit for you, please contact me with: 1) a paragraph about your experience to date, 2) a paragraph about your research interests, 3) a paragraph about why you are pursuing a graduate degree, and why you believe the lab is a good fit for you, 4) information about your current or potential funding situation, and 5) a current CV.

I accept graduate students through either the [Sustainable Fisheries Graduate Program](https://manoa.hawaii.edu/fisheries/) or the [Marine Biology Graduate Program](https://manoa.hawaii.edu/marinebiograd/). Please indicate which program you are interested in when you contact me. 

Funding will be critical to the success of your application, your studies, as well as your research. I actively fundraise for lab-wide projects, some of which may include available opportunities to fund graduate students. If such opportunities are available they will be listed above. Otherwise, it is possible for you to pursue your own funding through fellowships such as  [NSF GRFP](http://www.nsfgrfp.org/), [NDSEG](https://ndseg.sysplus.com/), [EPA STAR](https://www.epa.gov/research-grants), [NOAA Nancy Foster](http://fosterscholars.noaa.gov/), and [NOAA/SG Population & Ecosystem Dynamics](https://seagrant.noaa.gov/NMFS-SG-Fellowship). Include whether you are planning to, or currently applying to, any fellowships when you contact me.

### **Postdoctoral Researchers**

If your research interests align with the lab’s, and you are interested in doing a postdoc with the lab, please feel free to contact me. If funding is available I will post recruitment information above and on social media. Otherwise, if you have an idea for a project that you think we could collaborate on please reach out to me, and consider opportunities to apply for funding such as: [Smith Fellowships](https://conbio.org/mini-sites/smith-fellows), [NSF Postdoctoral Fellowship in Biology](https://www.nsf.gov/funding/pgm_summ.jsp?pims_id=503622), the [Ford Foundation](https://sites.nationalacademies.org/pga/fordfellowships/pga_171940), [L’Oreal](https://www.lorealusa.com/csr-commitments/l%E2%80%99or%C3%A9al-usa-for-women-in-science-program), [Life Science Research Foundation](http://www.lsrf.org/). Others are listed [here](http://www.des.ucdavis.edu/faculty/baskett/links/academia.html#Postdoc) (maintained by Marissa Baskett). When contacting me, please include: a brief description of your experience (1 paragraph) and your ideas for work in the lab (1 paragraph), your CV, and the names of at least two references.

### **Undergraduate Students**

Positions for undergraduate research opportunities will be posted here as they become available.
